### PR TITLE
Completed CheckList for TeamADGuy

### PR DESCRIPTION
**Pull request by PradoVarathan**

### CODE REVIEW

**Comment by sdhutchins** [comment]
Hey, can you make sure your repository is public?

**Comment by sdhutchins** [comment]
Just pinging again, @PradoVarathan.

**Comment by sdhutchins** [comment]
Also, @PradoVarathan, please update your [team members](https://github.com/u-brite/TeamADGuy#team-members) section: you can simply have yourself there to start. 

Thanks for making the repo public and getting some basic information there. 😄

**Comment by PradoVarathan** [comment]
@sdhutchins Sorry for the delayed response. I corrected it all

**Comment by sdhutchins** [comment]
No worries @PradoVarathan !!! Thanks! Looks great.

**Pull request merged**
